name: Schedule Python Script

on:
  schedule:
    - cron: "0 1 * * *" # Script runs every day at 1 am.
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Create Virtual Environment
        run: |
          python3 -m venv venv

      - name: Activate Virtual Environment and Install Dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Installed Packages
        run: |
          source venv/bin/activate
          pip list  

      - name: Verify Virtual Environment
        run: |
          source venv/bin/activate
          python -c "import sys; print(sys.prefix)"

      - name: Check for googleapiclient (Within Virtual Environment)
        run: |
          source venv/bin/activate
          python -c "import sys; print('googleapiclient' in sys.modules)"

      - name: Decode and save service account file
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          echo "${SERVICE_ACCOUNT_JSON}" > service_account.json

      - name: Run Python script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
        run: |
          source venv/bin/activate  # Ensure the virtual environment is activated here as well.
          python main.py

      - name: Clean up credentials file
        run: rm service_account.json

